GeneralSettings:
  Token: "MTQ1OTcwNTY3MTk1OTQ0OTcxNA.GxWwLE.Pa33jnjXg1ahbN7f8KFkg8f0sAgin5NJBIZTeU"
  EmbedColor: "#E74C3C"

ActivitySettings:
  Enabled: true
  Activities:
    - ["Watching", "heiznerd", "heiznerd"]
    - ["Playing", "heiznerd", "heiznerd"]
  Interval: "1m"

DatabaseSettings:
  Uri: "mongodb://localhost/Absolet"